### ISSUE TITLE
Confusion regarding "StartWithMatchScore" step, inputDir  vs controlsDir 

### ISSUE THREAD

**Issue by npatel-ah** [molgenis/CoNVaDING#49]
Hello, 

I am a little confused with the right files to be used for the "StartWithMatchScore". 
As per the document "https://molgenis.gitbook.io/convading/#startwithmatchscore" there are 3 input directories

controlsDir : This is clear we used the controls generated in first steps *.aligned.only.normalized.coverage.txt   
outputDir:  This is the output directory where the results will be stored.
inputDir: What is this directory? A directory with bam files or Normalized counts from the tumor samples?  

Thanks

**Comment by ljohansson** [comment]
The inputDir is the directory containing the *.aligned.only.normalized.coverage.txt files created in the previous step. The inputDir should contain the samples you would like to analyze. (the controlsDir and inputDir can in principle contain the normalized coverage files of the same samples.)

**Comment by npatel-ah** [comment]
Ohh I see, , the '-inputDir ' is more useful when you have additional controls which are not in "controlsDir " , otherwise controlsDir  and inputDir  will be same directory, 

Thanks for the quick response.
